import { useEffect } from 'react'

// Edit pillar content here.
// name: card title. detail: the paragraphs on the card. img: photo in /public or a full image URL.
const pillars = [
  {
    name: 'Innovation & Entrepreneurship',
    img: '/About-3.jpg',
    detail: [
      'The Innovation and Entrepreneurship pillar supports Global Shapers members in building technology-driven solutions to community challenges, fostering entrepreneurial thinking, and connecting Nairobi\'s young innovators to resources, networks, and opportunities.',
      'Projects under this pillar include our Food Wastage Solution, a platform to track and redistribute surplus food from hotels to communities in need, developed in partnership with PadMad and Woodland Star International School.',
      'The pillar also supports member-led initiatives in fintech, agritech, and civic tech, and organises industry linkage programmes that connect young professionals to Nairobi\'s growing startup ecosystem.',
    ],
  },
  {
    name: 'Education and Future of Work',
    img: '/project-technovation.JPG',
    detail: [
      'The Education and Future of Work pillar anchors Global Shapers Nairobi\'s longest-running and most impactful programme: Technovation. Since 2021, we have been delivering this global girls-in-tech competition to marginalised communities across Kenya, empowering over 300 girls with coding, entrepreneurship, and market research skills.',
      'Beyond Technovation, the pillar delivers the Financial Literacy Series, equipping young Nairobians with practical money management skills, and career mentorship sessions that connect members with experienced professionals.',
      'In 2024, our Technovation work earned us the Innovation Prize from the Global Shapers Community, Accenture, and the Global Alliance for YOUth, enabling us to scale to six new regions across Kenya.',
    ],
  },
  {
    name: 'Environment and Sustainability',
    img: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=900&q=80',
    detail: [
      'The Environment and Sustainability pillar addresses Nairobi\'s most pressing environmental challenges, from waste management and food systems to climate education and sustainable practices.',
      'This pillar is home to our newest project, the Food Wastage Solution, which addresses the significant food waste generated by Nairobi\'s hotels and restaurants by building a platform that tracks, reduces, and redistributes surplus food to communities in need.',
      'The pillar also organises community clean-up drives, advocates for climate policy, and partners with organisations working on environmental education for children and youth across Nairobi.',
    ],
  },
  {
    name: 'Underserved Communities',
    img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
    detail: [
      'Formerly known as Refugee Rights, this pillar has been broadened to encompass a wider range of projects serving marginalised and underserved communities across Nairobi, while remaining committed to the issues of displacement and civic rights that originally defined it.',
      'Dining in the Dark is the flagship project of this pillar, an immersive dining experience in complete darkness guided by visually impaired hosts from the Kenya Society for the Blind. The event builds empathy, raises funds, and advocates for the visually impaired community.',
      'The pillar also supports civic education initiatives, voter sensitisation campaigns, mental health partnerships for marginalised groups, and menstrual health and sanitary product drives for girls and women in underserved communities.',
    ],
  },
]

export default function PillarsPage() {
  useEffect(() => { window.scrollTo(0, 0) }, [])

  return (
    <div style={{ paddingTop: '4.5rem', background: 'var(--off-white)' }}>
      <section className="pp-hero">
        <div className="container">
          <h1>Explore our pillars</h1>
        </div>
      </section>

      <section className="pp-grid-wrap">
        <div className="container">
          <div className="pp-grid">
            {pillars.map((p, i) => (
              <article key={p.name} className="pc-card">
                <div className="pc-img">
                  <img src={p.img} alt="" loading={i < 2 ? 'eager' : 'lazy'} />
                </div>
                <div className="pc-content">
                  <span className="pc-label">Pillar {String(i + 1).padStart(2, '0')}</span>
                  <h2>{p.name}</h2>
                  {p.detail.map((d, j) => <p key={j}>{d}</p>)}
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <style>{`
        .pp-hero {
          text-align: center; color: var(--white);
          padding: clamp(4rem, 8vw, 6rem) 0 clamp(9rem, 16vw, 13rem);
          background:
            radial-gradient(circle at 20% 20%, rgba(30,91,201,0.55) 0%, transparent 45%),
            radial-gradient(circle at 85% 70%, rgba(0,172,193,0.18) 0%, transparent 45%),
            var(--blue-dark);
        }
        .pp-hero h1 { font-size: clamp(2.4rem, 6vw, 4.5rem); font-weight: 700; letter-spacing: -0.03em; line-height: 1.05; margin-bottom: 1.25rem; }
        .pp-hero h1 em { font-style: italic; font-weight: 300; }
        .pp-hero p { color: rgba(255,255,255,0.75); font-size: 1rem; line-height: 1.7; max-width: 520px; margin: 0 auto; }

        .pp-grid-wrap { padding-bottom: clamp(4rem, 8vw, 6rem); margin-top: clamp(-8rem, -12vw, -6rem); }
        .pp-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.75rem; max-width: 1000px; margin: 0 auto; }

        .pc-card {
          background: var(--white); border-radius: 20px; padding: 0.75rem 0.75rem 1.75rem;
          box-shadow: var(--shadow-sm); border: 1px solid var(--border);
          display: flex; flex-direction: column;
        }
        .pc-img { aspect-ratio: 16 / 10; border-radius: 14px; overflow: hidden; background: var(--blue-dark); margin-bottom: 1.5rem; }
        .pc-img img { width: 100%; height: 100%; object-fit: cover; }
        .pc-content { padding: 0 0.85rem; }
        .pc-label { display: block; font-size: 0.8rem; font-weight: 600; color: var(--blue); margin-bottom: 0.35rem; }
        .pc-content h2 { font-size: 1.3rem; font-weight: 700; color: var(--blue-dark); letter-spacing: -0.01em; line-height: 1.3; margin-bottom: 1rem; }
        .pc-content p { font-size: 0.9rem; line-height: 1.75; color: var(--text-mid); }
        .pc-content p + p { margin-top: 0.85rem; }

        @media (max-width: 800px) {
          .pp-grid { grid-template-columns: 1fr; max-width: 560px; }
        }
      `}</style>
    </div>
  )
}