import { useEffect } from 'react'

const pillars = [
  {
    name: 'Innovation and Entrepreneurship',
    color: 'var(--blue)',
    summary: 'Building tech solutions and fostering startup thinking across Nairobi.',
    detail: [
      'The Innovation and Entrepreneurship pillar supports Global Shapers members in building technology-driven solutions to community challenges, fostering entrepreneurial thinking, and connecting Nairobi\'s young innovators to resources, networks, and opportunities.',
      'Projects under this pillar include our Food Wastage Solution, a platform to track and redistribute surplus food from hotels to communities in need, developed in partnership with PadMad and Woodland Star International School.',
      'The pillar also supports member-led initiatives in fintech, agritech, and civic tech, and organises industry linkage programmes that connect young professionals to Nairobi\'s growing startup ecosystem.',
    ],
    projects: [],
  },
  {
    name: 'Education and Future of Work',
    color: 'var(--blue-dark)',
    summary: 'Equipping young people with the skills to thrive in a changing world.',
    detail: [
      'The Education and Future of Work pillar anchors Global Shapers Nairobi\'s longest-running and most impactful programme: Technovation. Since 2021, we have been delivering this global girls-in-tech competition to marginalised communities across Kenya, empowering over 300 girls with coding, entrepreneurship, and market research skills.',
      'Beyond Technovation, the pillar delivers the Financial Literacy Series, equipping young Nairobians with practical money management skills, and career mentorship sessions that connect members with experienced professionals.',
      'In 2024, our Technovation work earned us the Innovation Prize from the Global Shapers Community, Accenture, and the Global Alliance for YOUth, enabling us to scale to six new regions across Kenya.',
    ],
    projects: [],
  },
  {
    name: 'Environment and Sustainability',
    color: 'var(--teal)',
    summary: 'Driving climate action and building a greener Nairobi.',
    detail: [
      'The Environment and Sustainability pillar addresses Nairobi\'s most pressing environmental challenges, from waste management and food systems to climate education and sustainable practices.',
      'This pillar is home to our newest project, the Food Wastage Solution, which addresses the significant food waste generated by Nairobi\'s hotels and restaurants by building a platform that tracks, reduces, and redistributes surplus food to communities in need.',
      'The pillar also organises community clean-up drives, advocates for climate policy, and partners with organisations working on environmental education for children and youth across Nairobi.',
    ],
    projects: [],
  },
  {
    name: 'Underserved Communities',
    color: 'var(--blue-mid)',
    summary: 'Creating inclusive opportunities for marginalised groups in Nairobi.',
    detail: [
      'Formerly known as Refugee Rights, this pillar has been broadened to encompass a wider range of projects serving marginalised and underserved communities across Nairobi, while remaining committed to the issues of displacement and civic rights that originally defined it.',
      'Dining in the Dark is the flagship project of this pillar, an immersive dining experience in complete darkness guided by visually impaired hosts from the Kenya Society for the Blind. The event builds empathy, raises funds, and advocates for the visually impaired community.',
      'The pillar also supports civic education initiatives, voter sensitisation campaigns, mental health partnerships for marginalised groups, and menstrual health and sanitary product drives for girls and women in underserved communities.',
    ],
    projects: [],
  },
]

export default function PillarsPage() {
  useEffect(() => { window.scrollTo(0, 0) }, [])

  return (
    <div style={{ paddingTop: '5rem' }}>
      {/* Hero */}
      <div style={{ background: 'var(--blue)', padding: '4rem 0 5rem', textAlign: 'center' }}>
        <div className="container">
          <span className="eyebrow" style={{ color: 'rgba(255,255,255,0.7)' }}></span>
          <h1 style={{ color: '#fff', fontSize: 'clamp(2.2rem,5vw,4rem)', fontWeight: 800, lineHeight: 1.1, letterSpacing: '-0.02em', marginBottom: '1rem' }}>
            Our Four Pillars
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '1.05rem', maxWidth: 520, margin: '0 auto' }}>
            Everything we do at Global Shapers Nairobi is organised around four focus areas that guide our projects, partnerships, and community work.
          </p>
        </div>
      </div>

      {/* Pillars */}
      {pillars.map((p, i) => (
        <section key={p.name} style={{
          padding: 'clamp(3rem,6vw,5rem) 0',
          background: i % 2 === 0 ? 'var(--white)' : 'var(--off-white)',
          borderTop: '1px solid var(--border)',
        }}>
          <div className="container">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.6fr', gap: '4rem', alignItems: 'start' }} className="pillar-detail-grid">
              {/* Left */}
              <div>
                <div style={{ width: 56, height: 5, borderRadius: 3, background: p.color, marginBottom: '1.5rem' }}/>
                <span style={{ fontSize: '0.68rem', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: p.color, display: 'block', marginBottom: '0.5rem' }}>Pillar {String(i+1).padStart(2,'0')}</span>
                <h2 style={{ fontSize: 'clamp(1.5rem,3vw,2.2rem)', fontWeight: 800, color: 'var(--text-dark)', letterSpacing: '-0.02em', lineHeight: 1.2, marginBottom: '1rem' }}>{p.name}</h2>
                <p style={{ color: 'var(--text-mid)', fontSize: '1rem', lineHeight: 1.75, marginBottom: '2rem' }}>{p.summary}</p>
                <div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                    {p.projects.map(proj => (
                      <div key={proj} style={{ display: 'flex', alignItems: 'center', gap: '0.65rem', padding: '0.65rem 1rem', borderRadius: 8, background: 'var(--blue-light)', border: '1px solid var(--border)' }}>
                        <div style={{ width: 6, height: 6, borderRadius: '50%', background: p.color, flexShrink: 0 }}/>
                        <span style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--text-dark)' }}>{proj}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Right */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                {p.detail.map((d, j) => (
                  <p key={j} style={{ color: 'var(--text-mid)', fontSize: '0.975rem', lineHeight: 1.85 }}>{d}</p>
                ))}
              </div>
            </div>
          </div>
        </section>
      ))}

      <style>{`@media(max-width:768px){.pillar-detail-grid{grid-template-columns:1fr !important;gap:2.5rem !important}}`}</style>
    </div>
  )
}
